<?php $_histories = $this->getHistories(); ?>
<?php echo $this->getPagerHtml(); ?>
<?php if($_histories->getSize()): ?>
<table class="data-table" id="my-histories-table">
    <thead>
        <tr>
            <th width="5%">No.</th>
            <th width="15%"><?php echo $this->__('Action') ?></th>
            <th width="10%"><?php echo $this->__('Point Delta') ?></th>
            <th width="55%"><?php echo $this->__('Comment') ?></th>
            <th width="15%"><span class="nobr"><?php echo $this->__('Date') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_histories as $_h): ?>
        <tr>
            <td><?php echo $_h->getRefId() ?></td>
            <td><?php echo $_h->getAction() ?></td>
            <?php if ($_h->getPoint() > 0): ?>
                <td class="nobr">+<?php echo number_format($_h->getPoint()) ?>pt</td>
            <?php else: ?>
                <td class="nobr"><?php echo number_format($_h->getPoint()) ?></td>
            <?php endif ?>
            <td><?php echo $_h->getComment() ?></td>
            <td><?php echo $_h->getCreatedAtFormated() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-histories-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no point transaction history.'); ?></p>
<?php endif ?>
