<div class="h3_point">
<h3>お客様のポイント</h3>
<div class="h3_point_inner">
<div class="user_point">
<?php
$point = $this->formatPoint($this->getCurrentBalance());
if(!isset($point) || empty($point)):
?>
<p>ログインするとポイントを確認できます。</p>
<p class="user_btn">
<a href="/magento/index.php/rackpoint/account/">ログイン新規登録はこちら</a>
</p>
<?php else: ?>
<p class="dashbord_p01">お客様のポイント<br><strong style="font-size:16px;"><?php echo $point; ?></strong></p>
<p class="user_btn">
<a href="/magento/index.php/rackpoint/account/">ポイントの詳細はこちら</a>
</p>
<?php endif; ?>
</div>

</div>
</div>