<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-calendar"><?php echo Mage::helper('calendar')->__('Calendar Manager') ?></h3></td>
        <td class="a-right">
           <?php echo $this->getInitButtonHtml() ?> 
           <?php echo $this->getAddNewButtonHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php echo $this->getStoreSwitcherHtml() ?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
