<?php
/*
 * Irvine Systems Award Points
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Revised BSD License which is bundled with
 * this package in the files LICENSE.txt and LICENSE.html.
 *
 * @category    Magento Sale Extension
 * @package        IrvineSystems_AwardPoints
 * @author Irvine Systems, Inc.
 * @copyright Copyright (c) 2015, Irvine Systems, Inc. (http://irvinesystems.co.jp/)
 * @license     Revised BSD License
 */
?>

<?php // Helper Definition ?>
<?php $helper = Mage::helper('awardpoints');?>

<div class="page-title">
    <h1><?php echo $helper->__('Shopping Points') ?></h1>
</div>
<div class="fieldset">
	<h2 class="legend"><?php echo $helper->__('Your Shopping Points History') ?></h2>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<?php $_points = $this->getPoints();?>
	<?php if($_points->getSize()): ?>
		<?php echo $this->getPagerHtml() ?>

		<table cellspacing="0" class="data-table" id="award-points-table">
			<thead>
				<tr>
					<th><?php echo $helper->__('Type of Point') ?></th>
					<th><?php echo $helper->__('Points Gained') ?></th>
					<th><?php echo $helper->__('Points Used') ?></th>
					<th><?php echo $helper->__('Obtainment Date') ?></th>
					<th><?php echo $helper->__('Expiration Date') ?></th>
				</tr>
			</thead>
			<tbody>
				<?php $_odd = ''; ?>
				<?php foreach ($_points as $_point): ?>
				<tr>
					<td><?php echo $this->getTypeOfPoint($_point->getData());?></td>
					<td><?php echo $_point->getPoints_current() ?></td>
					<td><?php echo $_point->getPoints_spent() ?></td>
					<td><?php if ($_point->getDate_start() != ""): echo $this->formatDate($_point->getDate_start(), 'short'); endif; ?></td>
					<td><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
		<?php echo $this->getPagerHtml() ?>
		<?php else: ?>
		<p><?php echo $helper->__('You dont have any points history.'); ?></p>
	<?php endif ?>
</div>