<?php
/*
 * Irvine Systems Award Points
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Revised BSD License which is bundled with
 * this package in the files LICENSE.txt and LICENSE.html.
 *
 * @category    Magento Sale Extension
 * @package        IrvineSystems_AwardPoints
 * @author Irvine Systems, Inc.
 * @copyright Copyright (c) 2015, Irvine Systems, Inc. (http://irvinesystems.co.jp/)
 * @license     Revised BSD License
 */
?>

<?php // Get Product Points Value ?>
<?php $productPoints =  Mage::helper('awardpoints/data')->getProductPoints($this->getProduct()); ?>
<?php if($productPoints):?>

	<?php // Helper Definition ?>
	<?php $helper = Mage::helper('awardpoints');?>


	<p class="arcanum-loyalty-points" style="top:50px">
		<img src="<?php echo $this->getSkinUrl('images/AwardPoints/AwardPoints.png') ?>" alt="" />
	    <span style="left:15px;">
	    	&nbsp;&nbsp;
			<?php echo $helper->__("Product Points: "); ?>
	        <?php echo sprintf("<span id='award-points'>%d</span>", $productPoints);?>
		</span>
	</p>

	<?php // Update the Point value when the quantity is updated ?>
	<script type="text/javascript">
	    document.observe("dom:loaded", function() {
	        if ($('qty')){
	            Event.observe($('qty'), 'change', function(){
					if($('qty').value > 0){
						$('award-points').innerHTML = <?php echo $productPoints ?> * $('qty').value;
					} else {
						$('award-points').innerHTML = <?php echo $productPoints ?>;
					}
				});
	        }
	    });
	</script>
<?php endif;?>
