<?php
/*
 * Irvine Systems Delivery Date Optimum
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Revised BSD License which is bundled with
 * this package in the files LICENSE.txt and LICENSE.html.
 *
 * @category	Magento Catalog Extension
 * @package		IrvineSystems_Deliverydate
 * @author Irvine Systems, Inc.
 * @copyright Copyright (c) 2015, Irvine Systems, Inc. (http://irvinesystems.co.jp/)
 * @license     Revised BSD License
 */
?>
<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php  $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?></h2>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $_order->getShippingDescription() ?>
                        
					<?php // DELIVERY DATE IMPLEMENBTATION  -  START ?>
	                <?php  
					// Get Config and Set Default Values
					$date_format		= Mage::getStoreConfig('deliverydate/general/date_format');
					$deliveryDate		= Mage::helper('deliverydate')->__('N/A');
					$deliveryTime		= Mage::helper('deliverydate')->__('N/A');
					$deliveryComments	= Mage::helper('deliverydate')->__('N/A');
						
                    // If values are available det the Values
                    if ($date_format=='') $date_format='d/M/Y';
					if ($_order->getShippingDeliveryDate()!='') $deliveryDate = date ($date_format,strtotime($_order->getShippingDeliveryDate()));
					if ($_order->getShippingDeliveryTime()!='') $deliveryTime = $_order->getShippingDeliveryTime();
					if ($_order->getShippingDeliveryComments()!='') $deliveryComments = $_order->getShippingDeliveryComments();

                    // Print The Results
                    echo "<br/>";
					echo Mage::helper('deliverydate')->__('Shipping Delivery Date: %s', $deliveryDate);
                    echo "<br/>";
					echo Mage::helper('deliverydate')->__('Shipping Delivery Time: %s', $deliveryTime);
                    echo "<br/>";
					echo Mage::helper('deliverydate')->__('Shipping Delivery Comments: %s', $deliveryComments);
                    echo "<br/>";
	                ?>
    				<?php // DELIVERY DATE IMPLEMENBTATION  -  END ?>
                    
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>