<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h2 class="h2_heading"><?php echo $this->__('My Orders') ?></h2>
</div>
<div id="category">
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<section id="order">
                       <div class="select">
                           <div>
                           <p>表示</p>
                                <select name="number">
                                    <option value="10">10件
                                    <option value="15">15件
                                    <option value="20">20件
                                </select>
                            </div>
                        </div>
                         <p class="display">1件目～1件目まで表示 (全1件中)</p>
<table>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>
            <th><?php echo $this->__('Order Total') ?></th>
            <th><?php echo $this->__('Order Status') ?></th>
<!--            <th>&nbsp;</th>-->
        </tr>
    
    
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td><?php echo $_order->getRealOrderId() ?></td>
            <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td><?php echo $_order->getStatusLabel() ?></td>
<!--            <td></td>-->
        </tr>
        <?php endforeach; ?>
 </table>
    <div class="order_link">
        <ul>
            <li><a href="<?php echo $this->getViewUrl($_order) ?>">注文の詳細を表示</a></li>
            <li>｜</li>
            <li><a href="<?php echo $this->getReorderUrl($_order) ?>">再注文</a></li>
        </ul>
    </div>
                        <div class="select">
                           <div>
                           <p>表示</p>
                                <select name="number">
                                    <option value="10">10件
                                    <option value="15">15件
                                    <option value="20">20件
                                </select>
                            </div>
                            </div>
                            <p class="display">1件目～1件目まで表示 (全1件中)</p>
    </section>
<!--<script type="text/javascript">decorateTable('my-orders-table');</script>-->
<?php echo $this->getPagerHtml(); ?>
<div class="back_btn"><!-- 前のページに戻る -->
<a href="javascript:history.back();"><p class="arr"></p><p class="arr_txt">前のページに戻る</p></a>
</div>
<?php else: ?>
<p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
</div>
