<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h2 class="h2_heading"><?php echo $this->__('My Orders') ?></h2>
</div>
<section id="order">
<div class="select">
<?php echo $this->getPagerHtml(); ?>
</div>
<?php if($_orders->getSize()): ?>
<table>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>
            <th><?php echo $this->__('Order Total') ?></th>
            <th><?php echo $this->__('Order Status') ?></th>
            <th>&nbsp;</th>
        </tr>
    
    
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
			<td><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
            <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td><?php echo $_order->getStatusLabel() ?></td>
            <td>
				<ul class="order_link">
					<li><a href="<?php echo $this->getViewUrl($_order) ?>">詳細を表示</a></li>
					<li><a href="<?php echo $this->getReorderUrl($_order) ?>">再注文</a></li>
					<?php if ($this->helper('cancelorder/customer')->canCancel($_order)) : ?>
						<li><a href="<?php echo $this->getUrl('sales/order/cancel', array('order_id' => $_order->getId())) ?>"><?php echo $this->__('Cancel') ?></a></li>
					<?php endif ?>
				</ul>
            </td>
        </tr>
        <?php endforeach; ?>
 </table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<div class="select">
<?php echo $this->getPagerHtml(); ?>
</div>
<?php else: ?>
<p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
</section>
