<!--<div class="box-account box-recent">-->
<?php $_orders = $this->getOrders(); ?>
    <div class="page-title">
<h2 class="dashbord_sub"><?php echo $this->__('Recent Orders') ?></h2>
<?php /*
   <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
*/?>
</div>
    
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <section id="orders">
 <table>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th>配送先</th>
            <th><?php echo $this->__('Order Total') ?></th>
            <th><?php echo $this->__('Order Status') ?></th>
           <th>&nbsp;</th>
        </tr>
    
    
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <tr>
			<td><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
            <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td><?php echo $_order->getStatusLabel() ?></td>
            <td><a href="<?php echo $this->getReorderUrl($_order) ?>">再注文</a></td>
        </tr>
        <?php endforeach; ?>
 </table>                </tr>
<!--    <div class="order_link">
        <ul>
            <li><a href="<?php echo $this->getViewUrl($_order) ?>">注文の詳細を表示</a></li>
            <li><a href="<?php echo $this->getReorderUrl($_order) ?>">再注文</a></li>
        </ul>
    </div> -->
    </section>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
<!--</div>-->
