<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<li>
<label for="<?php echo $_code ?>_dc_cc" class="required"><em>*</em><?php echo $this->__('Number of payments') ?></label>
<div class="input-box">
<select id="<?php echo $_code ?>_dc_cc" name="payment[dc_cc]" class="required-entry">
<option value=""><?php echo $this->__('--Please Select--')?></option>
<?php $_dcCc = $this->getInfoData('dc_cc') ?>
<?php foreach ($this->getStoreNumber() as $_ccCode => $_ccName): ?>
<option value="<?php echo $_ccCode ?>"<?php if($_ccCode==$_dcCc): ?> selected="selected"<?php endif ?>><?php echo $_ccName ?></option>
<?php endforeach ?>
</select>
</div>
</li>
</ul>


