<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Review
 */
?>
<?php $reviews = $this->getReviews() ?> 
<?php if ($reviews && $reviews->count() > 0) : ?>
<div class="sideBox">
    <div class="h3_gray_bg"><h3>レビュー</h3></div>
    <div class="gray_bg">
        <?php foreach ($reviews as $review): ?>
        <div class="h3_point_inner">
             <dl>
            <?php $reviewUrl = Mage::getUrl('review/product/list/id/', array('id'=> $review->getId())); ?>
                    <dt><a href="<?php echo $reviewUrl; ?>"><img src="<?php echo $this->helper('catalog/image')->init($review, 'thumbnail')->resize(80) ?>" alt="<?php echo $this->htmlEscape($review->getName()) ?>" width="80" height="80" /></a></dt>
                    <dd><a href="<?php echo $reviewUrl; ?>"><?php echo $this->htmlEscape($review->getName())?></a></dd>
             </dl>
        <?php if (count($review->getRatingVotes())): ?>
        <table class="ratings-list" cellspacing="0">
            <tbody>
                <?php foreach ($review->getRatingVotes() as $_vote): ?>
                <tr>
                    <td class="label"><?php echo $_vote->getRatingCode() ?>:</td>
                    <td>
                        <div class="rating-box">
                            <div class="rating" style="width: <?php echo $_vote->getPercent() ?>%;"></div>
                        </div>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <?php endif;?>
             <p class="view"><span><?php echo $this->htmlEscape($review->getDetail())?></span></p>
        </div>
        <?php endforeach ?>
    </div>
</div>
<?php endif; ?>
