                   <div class="box">                
                       <p class="mb05"><img src="<?php echo $this->getSkinUrl('images/left_banner.png'); ?>"></p>
                           <ul class="accordion">
                              <li>
                               <p><span>スポーツスター</span></p>
                               <ul>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/drag-xl.html">ヒロチー/DRAGパーツ XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-65.html">クリアキン XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-66.html">ローランドサンズ XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-68.html">ジョーカーマシン XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-69.html">シート XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-70.html">マフラー XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/efi-xl.html">キャプ/EFI/エアクリ XL </a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-71.html">キジマ XL</a></li>
                                   <li><a href="http://airily.sixcore.jp/magento/index.php/harley-davidson/sportsstar/xl-72.html">デイトナ/ポッシュ XL</a></li>
                               </ul>
                           </li>
                           <li>
                               <p><span>ダイナ</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ソフテイル</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ツーリング モデル</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>VRSC モデル</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ストリート モデル</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ドラッグスペシャル</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>バイカーズチョイス</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                       </ul>
                       <p class="mb05"><img src="<?php echo $this->getSkinUrl('images/box_title02.png'); ?>"></p>
                        <ul class="accordion">
                          
                           <li>
                               <p><span>ヒロチーオリジナル</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ヒロチー 4スト ミニ</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ヒロチー スクーター</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>純正部品／用品</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>国内メーカー部品／用品</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>
                           </li>-->
                           <li>
                               <p><span>国内メーカーマフラー</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>海外メーカー</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>海外マフラー</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
</ul>
                      
                       <p class="mb05"><img src="<?php echo $this->getSkinUrl('images/box_title03.png'); ?>"></p>
                           <ul class="accordion">
                               <li>
                               <p><span>ツーリング用品</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>ヘルメット</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>
                           </li>-->
                           <li>
                               <p><span>アパレル</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>バッグ</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
</ul>
                       <p class="mb05"><img src="<?php echo $this->getSkinUrl('images/box_title04.png'); ?>"></p>
      <ul class="accordion">
                                                    <li>
                               <p><span>オイル／ケミカル</span></p>
                               <ul><li>登録がありません</li></ul>
                              <!-- <ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>
                           </li>-->
                           <li>
                               <p><span>工具／ジャッキ</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>
                           </li>-->
                           <li>
                               <p><span>セキュリティ</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
                           <li>
                               <p><span>その他</span></p>
                               <ul><li>登録がありません</li></ul>
                               <!--<ul>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                                   <li><a href="#">メニュー</a></li>
                               </ul>-->
                           </li>
</ul>

                       <!-- accordion -->
                       

                      
<?php
/*
                       <div class="calender">
                          <img src="<?php echo $this->getSkinUrl('images/calendar_02.png'); ?>">
                           <p><img src="<?php echo $this->getSkinUrl('images/cal_red.png'); ?>">休業日</p>
                           <p><img src="<?php echo $this->getSkinUrl('images/cal_yellow.png'); ?>">配送のみ</p>
                       </div>
*/
?>
</div>
                   <!-- box -->

               
               left_col
               
               <?php
 //*****************ココ以下にパーツブロック振り分けを入れる**********************//
$dataCurrentPage = $this->getHelper('cms/page')->getPage()->getData();
//var_dump($dataCurrentPage);
//$customPageID = $dataCurrentPage['identifier']);
if('8' == $dataCurrentPage['page_id']) :
 //*****管理画面で作成したブロックの指定　IDを配列に入れて処理**************//
    echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('12')->toHtml();
 
endif;
// 
?>

<!--left--><?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('12')->toHtml(); ?>