<div class="box">
<p class="mb05"><img src="<?php echo $this->getSkinUrl('images/left_banner.png'); ?>"></p>
<ul class="accordion">
<p><span><a href="">HARLEY-DAVIDSON</a></span></p>
<li>
<p><span>スポーツスター</span></p>
<ul>
	<li><a href="">スポーツスター</a></li>
	<li><a href="">ヒロチー/DRAGパーツ XL</a>
	<li><a href="">ヒロチー/DRAGパーツ XL</a></li>
	<li><a href="">クリアキン XL</a></li>
	<li><a href="">パフォーマンスマシン XL</a></li>
	<li><a href="">ローランドサンズ XL</a></li>
	<li><a href="">アレンネス XL</a></li>
	<li><a href="">ジョーカーマシン XL</a></li>
	<li><a href="">シート XL</a></li>
	<ul>
		<li><a href="">ラペラ XL</a></li>
		<li><a href="">マスタング XL</a></li>
	</ul>
</li>
<li><a href="">マフラー XL</a>
<ul>
	<li><a href="">バンス＆ハインズ /XL</a></li>
	<li><a href="">フリーダム パフォーマンス /XL</a></li>
	<li><a href="">クロームワークス、パイソン、S&S、サイクルシャック /XL</a></li>
	<li><a href="">スーパートラップ、カーカー、アクラポビッチ /XL</a></li>
	<li><a href="">サンダーヘッダー、コブラ、バッサニ、サムソン、バウコ /XL</a></li>
	<li><a href="">共通 マフラーガスケット、消耗品 /XL</a></li>
	<li><a href="">キジマ、ポッシュ、デイトナ、バッフル等 /XL</a></li>
</ul>
</li>
	<li><a href="">キャプ/EFI/エアクリ XL</a></li>
	<li><a href="">キジマ XL</a></li>
	<li><a href="">デイトナ/ポッシュ XL</a></li>
</li>
</ul>
</li>
<li>
<p><span>ダイナ</span></p>
<ul>
	<li><a href="">ヒロチー/DRAGパーツ Dyna</a></li>
	<li><a href="">クリアキン Dyna</a></li>
	<li><a href="">パフォーマンスマシン Dyna</a></li>
	<li><a href="">ローランドサンズ Dyna</a></li>
	<li><a href="">アレンネス Dyna</a></li></a></li>
	<li><a href="">ジョーカーマシン Dyna</a>
	<li><a href="">ラペラ Dyna</a></li>
	<li><a href="">マスタング Dyna</a></li>
	</li>
</ul>
</li>
<li>
<p><span>ソフテイル</span></p>
<ul>
	<li><a href="">ヒロチー/DRAGパーツ Softail</a></li>
	<li><a href="">クリアキン Softail</a></li>
	<li><a href="">パフォーマンスマシン Softail</a></li>
	<li><a href="">ローランドサンズ Softail</a></li>
	<li><a href="">アレンネス Softail</a></li>
	<li><a href="">ジョーカーマシン Softail</a></li>
	<li><a href="">シート Softail</a>
		<ul>
			<li><a href="">ラペラ Softail</a></li>
			<li><a href="">マスタング Softail</a></li>
		</ul>
	</li>
<li><a href="">マフラー Softail</a></li>
	<li><a href="">バンス＆ハインズ /Softail</a></li>
	<li><a href="">フリーダム パフォーマンス /Softail</a></li>
	<li><a href="">ラインハート /Softail</a></li>
	<li><a href="">クロームワークス、サイクルシャック/Softail</a></li>
	<li><a href="">スーパートラップ、カーカー /Softail</a></li>
	<li><a href="">パイソン、S&S、バッサニ /Softail</a></li>
	<li><a href="">サンダーヘッダー、コブラ、サムソン、バウコ /Softail</a></li>
	<li><a href="">クリアキン、アクラポビッチ Softail</a></li>
	<li><a href="">共通 マフラーガスケット、消耗品 /Softail</a></li>
	<li><a href="">キジマ、ポッシュ、デイトナ、バッフル等 /Softail</a></li>

<li><a href="">キャプ/EFI/エアクリ Softail</a></li>
<li><a href="">キジマ Softail</a></li>
<li><a href="">デイトナ/ポッシュ Softail</a></li>

</ul>
</li>
<li>
<p><span>ツーリング モデル</span></p>
<ul>
ヒロチー/DRAGパーツ Touring
クリアキン Touring
パフォーマンスマシン Touring
ローランドサンズ Touring
アレンネス Touring
ジョーカーマシン Touring
シート Touring
	ラペラ Touring
	マスタング Touring

マフラー Touring
	バンス＆ハインズ /Touring
	フリーダム パフォーマンス ツーリング
	ラインハート マフラー Touring
	スーパートラップ、カーカー /Touring
	クロームワークス、サイクルシャック/Touring
	パイソン、S&S、バッサニ、クロック ワークス/Touring
	サンダーヘッダー、コブラ、サムソン、バウコ /Touring
	クリアキン、アクラポビッチ Touring
	パフォーマンスマシン
	共通 マフラーガスケット、消耗品 / Touring
	キジマ、ポッシュ、デイトナ、バッフル等 /Touring

キャプ/EFI/エアクリ Touring
キジマ Touring
デイトナ/ポッシュ Touring

</ul>
</li>
<li>
<p><span>VRSC モデル</span></p>
<ul>
<li>
ヒロチー/DRAGパーツ VRSC
クリアキン VRSC
パフォーマンスマシン VRSC
ローランドサンズ VRSC
アレンネス VRSC
ジョーカーマシン VRSC
マフラー VRSC
エアクリーナ/EFI VRSC
キジマ VRSC
デイトナ/ポッシュ VRSC
ビューエル
</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>ストリート モデル</span></p>
<ul>
<li>ストリート モデル</li>
</ul>
<!-- <ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>ヘルメット/ アパレル/バック</span></p>
<ul>
<li>
【ヘルメット】メーカー別
	アライ
		フルフェイス
		オープンフェイス
		オフロード
		トライアル
		4輪レース
		ジュニアサイズ

	補修パーツ
		フルフェイスモデル用 シールド
		フルフェイスモデル用 システム内装
		フルフェイスモデル用 外装
		オープンフェイスモデル用 シールド
		オープンフェイスモデル用 システム内装
		オープンフェイスモデル用 外装
		オフロードモデル用 シールド
		オフロードモデル用 システム内装
		オフロード用 外装
		ベンチレーション用ダクト
		アクセサリーパーツ
		その他パーツ

	新規
		ヘルメット
		補修パーツ

	山城×アライ
		ヘルメット
		補修パーツ
ショウエイ（SHOEI)
	フルフェイスタイプ
	システムタイプ
	ジェットタイプ
	オフロードタイプ
	トライアルタイプ
	オプション＆パーツ
		シールド
		バイザー
		内装
		シールドベース
		ノーズカバー/シールドカバー
		ベンチレーション
		ブレスガード/エアマスク/チンカーテン
		スクリュー/レバー
		アクセサリー
	オージーケーカブト（OGK KABUTO）
		フルフェイスタイプ
		システムタイプ
		ジェットタイプ
		ハーフタイプ
		アフターパーツ
			フルフェイスタイプ
			システムタイプ
			ジェットタイプ
			ハーフタイプ
		アクセサリー
		アイコン(ICON)
			アイコン(ICON) ヘルメット
			アイコン(ICON) ヘルメット補修パーツ




</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>バイカーズチョイス</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
</ul>
<p class="mb05"><img src="<?php echo $this->getSkinUrl('images/box_title02.png'); ?>"></p>
<ul class="accordion">

<li>Japan 日本車</li>
<li>
<p><span>ヒロチーオリジナル</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>ヒロチー 4スト ミニ</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!-- <ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>ヒロチー スクーター</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>純正部品／用品</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>国内メーカー部品／用品</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>
</li>-->
<li>
<p><span>国内メーカーマフラー</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>海外メーカー</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>海外マフラー</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
</ul>

<p class="mb05"><img src="<?php echo $this->getSkinUrl('images/box_title03.png'); ?>"></p>
<ul class="accordion">
<li>各種バイク用品</li>
<li>
<p><span>ツーリング用品</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!-- <ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>ヘルメット</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>
</li>-->
<li>
<p><span>アパレル</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!-- <ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>バッグ</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!-- <ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
</ul>
<p class="mb05"><img src="<?php echo $this->getSkinUrl('images/box_title04.png'); ?>"></p>
<ul class="accordion">
<li>オイル／工具</li>
<li>
<p><span>オイル／ケミカル</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!-- <ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>
</li>-->
<li>
<p><span>工具／ジャッキ</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>
</li>-->
<li>
<p><span>セキュリティ</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
<li>
<p><span>その他</span></p>
<ul>
<li>登録がありません</li>
</ul>
<!--<ul>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
<li><a href="#">メニュー</a></li>
</ul>-->
</li>
</ul>

<!-- accordion -->




</div>
<!-- box -->



<?php /*               
<?php
//*****************ココ以下にパーツブロック振り分けを入れる
$dataCurrentPage = $this->getHelper('cms/page')->getPage()->getData();
//var_dump($dataCurrentPage);
//$customPageID = $dataCurrentPage['identifier']);
if('8' == $dataCurrentPage['page_id']) :
//*****管理画面で作成したブロックの指定　IDを配列に入れて処理
echo Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('12')->toHtml();

endif;
// 
?>
*/ ?>
<!--left-->