<div class="box">
<div class="infomation">
   <img src="<?php echo $this->getSkinUrl('images/infomation.png'); ?>">
   <div class="info_box">
	   <a href="<?php echo $this->getUrl('order'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_01.png'); ?>">
			   <p>ご注文方法</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('howtouse'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_02.png'); ?>">
			   <p>ショッピングカート<br>の利用手順</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('delivery'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_03.png'); ?>">
			   <p>配送について</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('shop'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_04.png'); ?>">
			   <p>店舗紹介</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('ask'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_05.png'); ?>">
			   <p>よくあるご質問</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('privacypolicy'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_06.png'); ?>">
			   <p>プライバシーポリシー</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('tradelaw'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_07.png'); ?>">
			   <p>特定商取引法に<br>基づく表記</p>
		   </section>
	   </a>
	   <a href="<?php echo $this->getUrl('aboutus'); ?>">
		   <section>
			   <img src="<?php echo $this->getSkinUrl('images/infomation_08.png'); ?>">
			   <p>会社概要</p>
		   </section>
	   </a>
   </div>
   <!-- info_box -->
</div>
<!-- infomation -->

</div>
<!-- box -->
